# language: generic 
# ( use this if if your travis build fails with “rakefile not found” )
sudo: required
services:
  - docker

before_install:
  - docker build -t dannythestreet/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dannythestreet/react-test npm test

after_success:
  - docker build -t dannythestreet/multi-client ./client
  - docker build -t dannythestreet/multi-nginx ./nginx
  - docker build -t dannythestreet/multi-server ./server
  - docker build -t dannythestreet/multi-worker ./worker



